### ISSUE TITLE
why date type data occur exception？

### ISSUE THREAD

**Issue by liudican** [oracle/tribuo#147]
load data.csv：
"2021-06-22",79.52
"2021-06-23",39.29
"2021-06-24",91.8

 String[] irisHeaders = new String[]{"date","xxx"};
        DataSource<Label> irisData =
                new CSVLoader<>(new LabelFactory()).loadDataSource(
                Paths.get("data.csv"),
                irisHeaders[1],
                irisHeaders);

Exception in thread "main" java.lang.NumberFormatException: For input string: "2021-06-22"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at org.tribuo.data.csv.CSVLoader.innerLoadFromCSV(CSVLoader.java:297)
	at org.tribuo.data.csv.CSVLoader.loadDataSource(CSVLoader.java:273)
	at org.tribuo.data.csv.CSVLoader.loadDataSource(CSVLoader.java:249)
	at org.tribuo.data.csv.CSVLoader.loadDataSource(CSVLoader.java:199)
	at cn.csc.iot.big.data.platform.ml.EiRegressModel.main(EiRegressModel.java:26)
thanks!

**Comment by Craigacp** [comment]
Tribuo's `CSVLoader` class is very simple and only loads in numeric data that can be converted into a float. If you want more control over the loading, for example to parse dates into features then you should use the `CSVDataSource` class and supply an appropriately configured `RowProcessor`. You can see how to use that in this [tutorial](https://tribuo.org/learn/4.1/tutorials/columnar-tribuo-v4.html).

**Comment by liudican** [comment]
ok，tanks
