### ISSUE TITLE
dll file not found for XGBoost framework?

### ISSUE THREAD

**Issue by nikkisingh111333** [oracle/tribuo#89]
hey .ddl file is not found in lib/ inside xgboost package.I have downloaded windows version of xgboost but cant find native .ddl lib file for xgboost how to solve this?

**Comment by Craigacp** [comment]
The upstream XGBoost4J artifact only contains binaries for Linux and macOS. As noted in the docs you'll need to compile it yourself to make it work with Windows. Internally we build XGBoost 1.0.0 for Windows and it works just fine. You might also be able to use the [Windows jars from Criteo](https://github.com/criteo-forks/xgboost-jars/releases), but they only have 1.1.0 and we've not tested that combination.

**Comment by nikkisingh111333** [comment]
so how can i use xgboost for now and test it out.i ve downloaded jars from criterio .?

**Comment by Craigacp** [comment]
Add them to your classpath, or as a maven/gradle dependency in whatever project you are building.

**Comment by nikkisingh111333** [comment]
i have added to my maven ...same error is happening..Jars have diffrent class name and giving me no configurable implemented error. i m using win64 jar . wht should i do now?

**Comment by Craigacp** [comment]
What's the exact stack trace and error message, and what does your classpath look like?

**Comment by nikkisingh111333** [comment]
this is the stack trace 
`Exception in thread "main" Property Exception component:'xgboost' - Class ml.dmlc.xgboost4j.java.XGBoost does not implement Configurable.
com.oracle.labs.mlrg.olcut.config.PropertyException: Component: xgboost, Class ml.dmlc.xgboost4j.java.XGBoost does not implement Configurable.
	at com.oracle.labs.mlrg.olcut.config.ConfigurationManager.getPropertySheet(ConfigurationManager.java:1227)
	at com.oracle.labs.mlrg.olcut.config.ConfigurationManager.innerLookup(ConfigurationManager.java:1367)
	at com.oracle.labs.mlrg.olcut.config.ConfigurationManager.lookup(ConfigurationManager.java:1357)
	at com.oracle.labs.mlrg.olcut.config.ConfigurationManager.lookup(ConfigurationManager.java:1300)
	at MachineLearningWithTRIBUO.TribuoML.DecisionTree(TribuoML.java:72)
	at MachineLearningWithTRIBUO.TribuoML.main(TribuoML.java:243)
`
heres my SS you can see left xgboost4j_2.1.1-xxxxxxxxxxx.jar 
![Screenshot (41)](https://user-images.githubusercontent.com/49682940/99431423-c0845880-2930-11eb-82d1-b50e0d1553e1.png)

**Comment by Craigacp** [comment]
If you want to use XGBoost with the configuration system then you should use Tribuo's XGBoost classes, `XGBoostClassificationTrainer` or `XGBoostRegressionTrainer`. They wrap the XGBoost4J classes and provide a Tribuo style interface. This isn't an issue with your classpath, it's an issue with the configuration file pointing at the wrong class.

**Comment by nikkisingh111333** [comment]
previously i was using the same XGBoostClassificationTrainer.heres my SS:
![Screenshot (42)](https://user-images.githubusercontent.com/49682940/99433511-9d0edd00-2933-11eb-87da-f4361dd74104.png)
Heres my original error after trying this config json xgboost :
`java.io.FileNotFoundException: File /lib/xgboost4j.dll was not found inside JAR.
	at ml.dmlc.xgboost4j.java.NativeLibLoader.createTempFileFromResource(NativeLibLoader.java:126)
	at ml.dmlc.xgboost4j.java.NativeLibLoader.loadLibraryFromJar(NativeLibLoader.java:69)
	at ml.dmlc.xgboost4j.java.NativeLibLoader.initXGBoost(NativeLibLoader.java:41)
	at ml.dmlc.xgboost4j.java.XGBoostJNI.<clinit>(XGBoostJNI.java:34)
	at ml.dmlc.xgboost4j.java.DMatrix.<init>(DMatrix.java:109)
	at org.tribuo.common.xgboost.XGBoostTrainer.convertExamples(XGBoostTrainer.java:309)
	at org.tribuo.classification.xgboost.XGBoostClassificationTrainer.train(XGBoostClassificationTrainer.java:142)
	at org.tribuo.classification.xgboost.XGBoostClassificationTrainer.train(XGBoostClassificationTrainer.java:62)
	at org.tribuo.Trainer.train(Trainer.java:44)
	at MachineLearningWithTRIBUO.TribuoML.DecisionTree(TribuoML.java:119)
	at MachineLearningWithTRIBUO.TribuoML.main(TribuoML.java:243)
Exception in thread "main" java.lang.ExceptionInInitializerError
	at ml.dmlc.xgboost4j.java.DMatrix.<init>(DMatrix.java:109)
	at org.tribuo.common.xgboost.XGBoostTrainer.convertExamples(XGBoostTrainer.java:309)
	at org.tribuo.classification.xgboost.XGBoostClassificationTrainer.train(XGBoostClassificationTrainer.java:142)
	at org.tribuo.classification.xgboost.XGBoostClassificationTrainer.train(XGBoostClassificationTrainer.java:62)
	at org.tribuo.Trainer.train(Trainer.java:44)
	at MachineLearningWithTRIBUO.TribuoML.DecisionTree(TribuoML.java:119)
	at MachineLearningWithTRIBUO.TribuoML.main(TribuoML.java:243)
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: File /lib/xgboost4j.dll was not found inside JAR.
	at ml.dmlc.xgboost4j.java.XGBoostJNI.<clinit>(XGBoostJNI.java:37)
	... 7 more
Caused by: java.io.FileNotFoundException: File /lib/xgboost4j.dll was not found inside JAR.
	at ml.dmlc.xgboost4j.java.NativeLibLoader.createTempFileFromResource(NativeLibLoader.java:126)
	at ml.dmlc.xgboost4j.java.NativeLibLoader.loadLibraryFromJar(NativeLibLoader.java:69)
	at ml.dmlc.xgboost4j.java.NativeLibLoader.initXGBoost(NativeLibLoader.java:41)
	at ml.dmlc.xgboost4j.java.XGBoostJNI.<clinit>(XGBoostJNI.java:34)
	... 7 more
`

**Comment by Craigacp** [comment]
You need to download the win64 jar. You downloaded the one without a type specifier which looks like it's only got a Linux binary in it.

**Comment by nikkisingh111333** [comment]
okk it solved...thanks for your support
